### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by PrantoshB** [PrantoshB/JavaScript-Capstone#21]
This is the Project Link for our JavaScript Capstone project:

https://github.com/users/PrantoshB/projects/5

Note: We are two people in our team.

**Comment by algerina** [comment]
Hi @PrantoshB, 
Unfortunately, I can not review your Kanban board the link to your project is not working. Please add a working link and submit it again.

**Comment by PrantoshB** [comment]
Hello @algerina, I have made the project public. Now you can view the project.

Thanks

**Comment by cynthiainga** [comment]
Hi @PrantoshB, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] The project link works correctly 👍 

## Required Changes ♻️

- [ ] Please kindly make sure all cards are assigned to team members 🙃 🙃 
See the example below:
<img width="359" alt="Screen Shot 2023-01-02 at 19 01 46" src="https://user-images.githubusercontent.com/74501523/210255101-7cfd0298-83a9-46f7-b8f0-7360cac52892.png">

- [ ] Cards should be assigned to team members in a fair way:
  - First, you need to decide who is `Student A`, and `Student B`. So each card with `Student A` in its title should be assigned to the same student (and analogical for `Student B`) 😉 
  - All cards with `group task` in the title should be assigned to someone 👍 
- [ ] Please kindly add more information about your team members by adding your github handles 🙃 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by FrederickMih** [comment]
## Hi :raising_hand: @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Cards are assigned to each team member in a fair manner :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
